# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eigGUI.ui'
#
# Created: Sun Dec  6 23:54:48 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.domainTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainTab.sizePolicy().hasHeightForWidth())
        self.domainTab.setSizePolicy(sizePolicy)
        self.domainTab.setObjectName(_fromUtf8("domainTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.domainTab)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.domains = QtGui.QListWidget(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domains.sizePolicy().hasHeightForWidth())
        self.domains.setSizePolicy(sizePolicy)
        self.domains.setMinimumSize(QtCore.QSize(300, 0))
        self.domains.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.domains.setObjectName(_fromUtf8("domains"))
        self.verticalLayout.addWidget(self.domains)
        self.label_2 = QtGui.QLabel(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.description = QtGui.QPlainTextEdit(self.domainTab)
        self.description.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(300, 200))
        self.description.setMaximumSize(QtCore.QSize(16777215, 200))
        self.description.setReadOnly(True)
        self.description.setObjectName(_fromUtf8("description"))
        self.verticalLayout.addWidget(self.description)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.parameters = QtGui.QComboBox(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters.sizePolicy().hasHeightForWidth())
        self.parameters.setSizePolicy(sizePolicy)
        self.parameters.setEditable(True)
        self.parameters.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.parameters.setObjectName(_fromUtf8("parameters"))
        self.verticalLayout_2.addWidget(self.parameters)
        self.meshFrame = QtGui.QFrame(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshFrame.sizePolicy().hasHeightForWidth())
        self.meshFrame.setSizePolicy(sizePolicy)
        self.meshFrame.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.meshFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshFrame.setObjectName(_fromUtf8("meshFrame"))
        self.verticalLayout_2.addWidget(self.meshFrame)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.domainTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.initSize = QtGui.QLineEdit(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initSize.sizePolicy().hasHeightForWidth())
        self.initSize.setSizePolicy(sizePolicy)
        self.initSize.setMinimumSize(QtCore.QSize(0, 0))
        self.initSize.setObjectName(_fromUtf8("initSize"))
        self.horizontalLayout_2.addWidget(self.initSize)
        self.label_5 = QtGui.QLabel(self.domainTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.initRefine = QtGui.QComboBox(self.domainTab)
        self.initRefine.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initRefine.sizePolicy().hasHeightForWidth())
        self.initRefine.setSizePolicy(sizePolicy)
        self.initRefine.setObjectName(_fromUtf8("initRefine"))
        self.initRefine.addItem(_fromUtf8(""))
        self.initRefine.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.initRefine)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.preview = QtGui.QPushButton(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setObjectName(_fromUtf8("preview"))
        self.horizontalLayout_2.addWidget(self.preview)
        self.solve = QtGui.QPushButton(self.domainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve.sizePolicy().hasHeightForWidth())
        self.solve.setSizePolicy(sizePolicy)
        self.solve.setObjectName(_fromUtf8("solve"))
        self.horizontalLayout_2.addWidget(self.solve)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabs.addTab(self.domainTab, _fromUtf8(""))
        self.transformTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformTab.sizePolicy().hasHeightForWidth())
        self.transformTab.setSizePolicy(sizePolicy)
        self.transformTab.setObjectName(_fromUtf8("transformTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.transformTab)
        self.verticalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.selectedTransforms = QtGui.QListWidget(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedTransforms.sizePolicy().hasHeightForWidth())
        self.selectedTransforms.setSizePolicy(sizePolicy)
        self.selectedTransforms.setMinimumSize(QtCore.QSize(300, 0))
        self.selectedTransforms.setDragEnabled(True)
        self.selectedTransforms.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.selectedTransforms.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.selectedTransforms.setObjectName(_fromUtf8("selectedTransforms"))
        self.verticalLayout_4.addWidget(self.selectedTransforms)
        self.label_9 = QtGui.QLabel(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.transformDescription = QtGui.QPlainTextEdit(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformDescription.sizePolicy().hasHeightForWidth())
        self.transformDescription.setSizePolicy(sizePolicy)
        self.transformDescription.setMaximumSize(QtCore.QSize(16777215, 150))
        self.transformDescription.setReadOnly(True)
        self.transformDescription.setObjectName(_fromUtf8("transformDescription"))
        self.verticalLayout_4.addWidget(self.transformDescription)
        self.label_7 = QtGui.QLabel(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.transforms = QtGui.QListWidget(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transforms.sizePolicy().hasHeightForWidth())
        self.transforms.setSizePolicy(sizePolicy)
        self.transforms.setObjectName(_fromUtf8("transforms"))
        self.verticalLayout_4.addWidget(self.transforms)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.updateTransformParams = QtGui.QPushButton(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTransformParams.sizePolicy().hasHeightForWidth())
        self.updateTransformParams.setSizePolicy(sizePolicy)
        self.updateTransformParams.setObjectName(_fromUtf8("updateTransformParams"))
        self.horizontalLayout_4.addWidget(self.updateTransformParams)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.transformParameters = QtGui.QLineEdit(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformParameters.sizePolicy().hasHeightForWidth())
        self.transformParameters.setSizePolicy(sizePolicy)
        self.transformParameters.setObjectName(_fromUtf8("transformParameters"))
        self.verticalLayout_6.addWidget(self.transformParameters)
        self.transformedMeshFrame = QtGui.QFrame(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformedMeshFrame.sizePolicy().hasHeightForWidth())
        self.transformedMeshFrame.setSizePolicy(sizePolicy)
        self.transformedMeshFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.transformedMeshFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.transformedMeshFrame.setObjectName(_fromUtf8("transformedMeshFrame"))
        self.verticalLayout_6.addWidget(self.transformedMeshFrame)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox = QtGui.QCheckBox(self.transformTab)
        self.checkBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.beforeAdaptive = QtGui.QCheckBox(self.transformTab)
        self.beforeAdaptive.setEnabled(False)
        self.beforeAdaptive.setObjectName(_fromUtf8("beforeAdaptive"))
        self.horizontalLayout_5.addWidget(self.beforeAdaptive)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.previewTransformed = QtGui.QPushButton(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewTransformed.sizePolicy().hasHeightForWidth())
        self.previewTransformed.setSizePolicy(sizePolicy)
        self.previewTransformed.setObjectName(_fromUtf8("previewTransformed"))
        self.horizontalLayout_5.addWidget(self.previewTransformed)
        self.solve2 = QtGui.QPushButton(self.transformTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve2.sizePolicy().hasHeightForWidth())
        self.solve2.setSizePolicy(sizePolicy)
        self.solve2.setObjectName(_fromUtf8("solve2"))
        self.horizontalLayout_5.addWidget(self.solve2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.tabs.addTab(self.transformTab, _fromUtf8(""))
        self.bcTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcTab.sizePolicy().hasHeightForWidth())
        self.bcTab.setSizePolicy(sizePolicy)
        self.bcTab.setObjectName(_fromUtf8("bcTab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.bcTab)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_10 = QtGui.QLabel(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10)
        self.selectedBC = QtGui.QListWidget(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedBC.sizePolicy().hasHeightForWidth())
        self.selectedBC.setSizePolicy(sizePolicy)
        self.selectedBC.setMinimumSize(QtCore.QSize(300, 0))
        self.selectedBC.setDragEnabled(True)
        self.selectedBC.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.selectedBC.setObjectName(_fromUtf8("selectedBC"))
        self.verticalLayout_7.addWidget(self.selectedBC)
        self.label_13 = QtGui.QLabel(self.bcTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_7.addWidget(self.label_13)
        self.bcDescription = QtGui.QPlainTextEdit(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcDescription.sizePolicy().hasHeightForWidth())
        self.bcDescription.setSizePolicy(sizePolicy)
        self.bcDescription.setMaximumSize(QtCore.QSize(16777215, 150))
        self.bcDescription.setReadOnly(True)
        self.bcDescription.setObjectName(_fromUtf8("bcDescription"))
        self.verticalLayout_7.addWidget(self.bcDescription)
        self.label_11 = QtGui.QLabel(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_7.addWidget(self.label_11)
        self.bcs = QtGui.QListWidget(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcs.sizePolicy().hasHeightForWidth())
        self.bcs.setSizePolicy(sizePolicy)
        self.bcs.setObjectName(_fromUtf8("bcs"))
        self.verticalLayout_7.addWidget(self.bcs)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.bcApplyTo = QtGui.QComboBox(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcApplyTo.sizePolicy().hasHeightForWidth())
        self.bcApplyTo.setSizePolicy(sizePolicy)
        self.bcApplyTo.setObjectName(_fromUtf8("bcApplyTo"))
        self.horizontalLayout_8.addWidget(self.bcApplyTo)
        self.bcParts = QtGui.QLineEdit(self.bcTab)
        self.bcParts.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcParts.sizePolicy().hasHeightForWidth())
        self.bcParts.setSizePolicy(sizePolicy)
        self.bcParts.setObjectName(_fromUtf8("bcParts"))
        self.horizontalLayout_8.addWidget(self.bcParts)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.bcLabel = QtGui.QLabel(self.bcTab)
        self.bcLabel.setObjectName(_fromUtf8("bcLabel"))
        self.horizontalLayout_9.addWidget(self.bcLabel)
        self.bcParameters = QtGui.QLineEdit(self.bcTab)
        self.bcParameters.setEnabled(True)
        self.bcParameters.setObjectName(_fromUtf8("bcParameters"))
        self.horizontalLayout_9.addWidget(self.bcParameters)
        self.updateBCParams = QtGui.QPushButton(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateBCParams.sizePolicy().hasHeightForWidth())
        self.updateBCParams.setSizePolicy(sizePolicy)
        self.updateBCParams.setObjectName(_fromUtf8("updateBCParams"))
        self.horizontalLayout_9.addWidget(self.updateBCParams)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.bcFrame = QtGui.QFrame(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcFrame.sizePolicy().hasHeightForWidth())
        self.bcFrame.setSizePolicy(sizePolicy)
        self.bcFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bcFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.bcFrame.setObjectName(_fromUtf8("bcFrame"))
        self.verticalLayout_9.addWidget(self.bcFrame)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.useTransformed = QtGui.QCheckBox(self.bcTab)
        self.useTransformed.setObjectName(_fromUtf8("useTransformed"))
        self.horizontalLayout_7.addWidget(self.useTransformed)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.previewBC = QtGui.QPushButton(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewBC.sizePolicy().hasHeightForWidth())
        self.previewBC.setSizePolicy(sizePolicy)
        self.previewBC.setObjectName(_fromUtf8("previewBC"))
        self.horizontalLayout_7.addWidget(self.previewBC)
        self.solve3 = QtGui.QPushButton(self.bcTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve3.sizePolicy().hasHeightForWidth())
        self.solve3.setSizePolicy(sizePolicy)
        self.solve3.setObjectName(_fromUtf8("solve3"))
        self.horizontalLayout_7.addWidget(self.solve3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.tabs.addTab(self.bcTab, _fromUtf8(""))
        self.otherTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherTab.sizePolicy().hasHeightForWidth())
        self.otherTab.setSizePolicy(sizePolicy)
        self.otherTab.setObjectName(_fromUtf8("otherTab"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.otherTab)
        self.horizontalLayout_13.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_3 = QtGui.QGroupBox(self.otherTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_14.addWidget(self.label_15)
        self.femType = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femType.sizePolicy().hasHeightForWidth())
        self.femType.setSizePolicy(sizePolicy)
        self.femType.setObjectName(_fromUtf8("femType"))
        self.femType.addItem(_fromUtf8(""))
        self.femType.addItem(_fromUtf8(""))
        self.femType.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.femType)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_14.addWidget(self.label_17)
        self.femDegree = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femDegree.sizePolicy().hasHeightForWidth())
        self.femDegree.setSizePolicy(sizePolicy)
        self.femDegree.setMinimumSize(QtCore.QSize(60, 0))
        self.femDegree.setMaximumSize(QtCore.QSize(60, 16777215))
        self.femDegree.setMinimum(1)
        self.femDegree.setMaximum(3)
        self.femDegree.setProperty("value", 2)
        self.femDegree.setObjectName(_fromUtf8("femDegree"))
        self.horizontalLayout_14.addWidget(self.femDegree)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        self.solveNumber = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solveNumber.sizePolicy().hasHeightForWidth())
        self.solveNumber.setSizePolicy(sizePolicy)
        self.solveNumber.setMinimumSize(QtCore.QSize(50, 0))
        self.solveNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.solveNumber.setMinimum(1)
        self.solveNumber.setMaximum(100)
        self.solveNumber.setProperty("value", 10)
        self.solveNumber.setObjectName(_fromUtf8("solveNumber"))
        self.horizontalLayout_11.addWidget(self.solveNumber)
        self.solveType = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solveType.sizePolicy().hasHeightForWidth())
        self.solveType.setSizePolicy(sizePolicy)
        self.solveType.setMinimumSize(QtCore.QSize(165, 0))
        self.solveType.setMaximumSize(QtCore.QSize(165, 16777215))
        self.solveType.setObjectName(_fromUtf8("solveType"))
        self.solveType.addItem(_fromUtf8(""))
        self.solveType.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.solveType)
        self.targetValue = QtGui.QLineEdit(self.groupBox_3)
        self.targetValue.setEnabled(False)
        self.targetValue.setObjectName(_fromUtf8("targetValue"))
        self.horizontalLayout_11.addWidget(self.targetValue)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.adaptive = QtGui.QCheckBox(self.groupBox_3)
        self.adaptive.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptive.sizePolicy().hasHeightForWidth())
        self.adaptive.setSizePolicy(sizePolicy)
        self.adaptive.setObjectName(_fromUtf8("adaptive"))
        self.horizontalLayout_23.addWidget(self.adaptive)
        self.torsion = QtGui.QCheckBox(self.groupBox_3)
        self.torsion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torsion.sizePolicy().hasHeightForWidth())
        self.torsion.setSizePolicy(sizePolicy)
        self.torsion.setObjectName(_fromUtf8("torsion"))
        self.horizontalLayout_23.addWidget(self.torsion)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.otherTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.meshLimit = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshLimit.sizePolicy().hasHeightForWidth())
        self.meshLimit.setSizePolicy(sizePolicy)
        self.meshLimit.setObjectName(_fromUtf8("meshLimit"))
        self.meshLimit.addItem(_fromUtf8(""))
        self.meshLimit.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.meshLimit)
        self.meshSize = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshSize.sizePolicy().hasHeightForWidth())
        self.meshSize.setSizePolicy(sizePolicy)
        self.meshSize.setObjectName(_fromUtf8("meshSize"))
        self.horizontalLayout_10.addWidget(self.meshSize)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_12.addWidget(self.label_14)
        self.refine = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refine.sizePolicy().hasHeightForWidth())
        self.refine.setSizePolicy(sizePolicy)
        self.refine.setObjectName(_fromUtf8("refine"))
        self.refine.addItem(_fromUtf8(""))
        self.refine.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.refine)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.snap = QtGui.QCheckBox(self.groupBox_2)
        self.snap.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap.sizePolicy().hasHeightForWidth())
        self.snap.setSizePolicy(sizePolicy)
        self.snap.setObjectName(_fromUtf8("snap"))
        self.horizontalLayout_15.addWidget(self.snap)
        self.snapType = QtGui.QComboBox(self.groupBox_2)
        self.snapType.setEnabled(False)
        self.snapType.setMinimumSize(QtCore.QSize(220, 0))
        self.snapType.setMaximumSize(QtCore.QSize(200, 16777215))
        self.snapType.setObjectName(_fromUtf8("snapType"))
        self.snapType.addItem(_fromUtf8(""))
        self.snapType.addItem(_fromUtf8(""))
        self.snapType.addItem(_fromUtf8(""))
        self.snapType.addItem(_fromUtf8(""))
        self.snapType.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.snapType)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_15.addWidget(self.label_18)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.snapFunction = QtGui.QLineEdit(self.groupBox_2)
        self.snapFunction.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapFunction.sizePolicy().hasHeightForWidth())
        self.snapFunction.setSizePolicy(sizePolicy)
        self.snapFunction.setMinimumSize(QtCore.QSize(400, 0))
        self.snapFunction.setMaximumSize(QtCore.QSize(400, 16777215))
        self.snapFunction.setObjectName(_fromUtf8("snapFunction"))
        self.verticalLayout_13.addWidget(self.snapFunction)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.otherTab)
        self.groupBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.adaptiveSnap = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptiveSnap.sizePolicy().hasHeightForWidth())
        self.adaptiveSnap.setSizePolicy(sizePolicy)
        self.adaptiveSnap.setObjectName(_fromUtf8("adaptiveSnap"))
        self.horizontalLayout_18.addWidget(self.adaptiveSnap)
        self.snapPercent = QtGui.QSpinBox(self.groupBox)
        self.snapPercent.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapPercent.sizePolicy().hasHeightForWidth())
        self.snapPercent.setSizePolicy(sizePolicy)
        self.snapPercent.setMinimumSize(QtCore.QSize(60, 0))
        self.snapPercent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.snapPercent.setMinimum(1)
        self.snapPercent.setMaximum(100)
        self.snapPercent.setProperty("value", 20)
        self.snapPercent.setObjectName(_fromUtf8("snapPercent"))
        self.horizontalLayout_18.addWidget(self.snapPercent)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_18.addWidget(self.label_21)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_19 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_17.addWidget(self.label_19)
        self.adaptivePercent = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptivePercent.sizePolicy().hasHeightForWidth())
        self.adaptivePercent.setSizePolicy(sizePolicy)
        self.adaptivePercent.setMinimumSize(QtCore.QSize(60, 0))
        self.adaptivePercent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.adaptivePercent.setMinimum(1)
        self.adaptivePercent.setProperty("value", 20)
        self.adaptivePercent.setObjectName(_fromUtf8("adaptivePercent"))
        self.horizontalLayout_17.addWidget(self.adaptivePercent)
        self.label_20 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_17.addWidget(self.label_20)
        self.adaptiveType = QtGui.QComboBox(self.groupBox)
        self.adaptiveType.setObjectName(_fromUtf8("adaptiveType"))
        self.adaptiveType.addItem(_fromUtf8(""))
        self.adaptiveType.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.adaptiveType)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_19.addWidget(self.label_22)
        self.residualType = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.residualType.sizePolicy().hasHeightForWidth())
        self.residualType.setSizePolicy(sizePolicy)
        self.residualType.setMinimumSize(QtCore.QSize(180, 0))
        self.residualType.setObjectName(_fromUtf8("residualType"))
        self.residualType.addItem(_fromUtf8(""))
        self.residualType.addItem(_fromUtf8(""))
        self.residualType.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.residualType)
        self.residualNumber = QtGui.QSpinBox(self.groupBox)
        self.residualNumber.setEnabled(False)
        self.residualNumber.setMinimum(1)
        self.residualNumber.setMaximum(100)
        self.residualNumber.setObjectName(_fromUtf8("residualNumber"))
        self.horizontalLayout_19.addWidget(self.residualNumber)
        spacerItem9 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.otherTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.weightTop = QtGui.QComboBox(self.groupBox_4)
        self.weightTop.setEditable(True)
        self.weightTop.setObjectName(_fromUtf8("weightTop"))
        self.weightTop.addItem(_fromUtf8(""))
        self.weightTop.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.weightTop)
        self.weightBottom = QtGui.QComboBox(self.groupBox_4)
        self.weightBottom.setEditable(True)
        self.weightBottom.setObjectName(_fromUtf8("weightBottom"))
        self.weightBottom.addItem(_fromUtf8(""))
        self.weightBottom.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.weightBottom)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.pushButton = QtGui.QPushButton(self.otherTab)
        self.pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.solve4 = QtGui.QPushButton(self.otherTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve4.sizePolicy().hasHeightForWidth())
        self.solve4.setSizePolicy(sizePolicy)
        self.solve4.setMinimumSize(QtCore.QSize(167, 0))
        self.solve4.setMaximumSize(QtCore.QSize(167, 16777215))
        self.solve4.setObjectName(_fromUtf8("solve4"))
        self.horizontalLayout_16.addWidget(self.solve4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.label_24 = QtGui.QLabel(self.otherTab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_24.addWidget(self.label_24)
        self.pushButton_3 = QtGui.QPushButton(self.otherTab)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_24.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.otherTab)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_24.addWidget(self.pushButton_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.label_23 = QtGui.QLabel(self.otherTab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_12.addWidget(self.label_23)
        self.stats = QtGui.QPlainTextEdit(self.otherTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats.sizePolicy().hasHeightForWidth())
        self.stats.setSizePolicy(sizePolicy)
        self.stats.setReadOnly(True)
        self.stats.setObjectName(_fromUtf8("stats"))
        self.verticalLayout_12.addWidget(self.stats)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.tabs.addTab(self.otherTab, _fromUtf8(""))
        self.solutionsTab = QtGui.QWidget()
        self.solutionsTab.setObjectName(_fromUtf8("solutionsTab"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.solutionsTab)
        self.horizontalLayout_21.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.solutionTabs = QtGui.QTabWidget(self.solutionsTab)
        self.solutionTabs.setUsesScrollButtons(True)
        self.solutionTabs.setDocumentMode(True)
        self.solutionTabs.setTabsClosable(True)
        self.solutionTabs.setMovable(True)
        self.solutionTabs.setObjectName(_fromUtf8("solutionTabs"))
        self.horizontalLayout_21.addWidget(self.solutionTabs)
        self.tabs.addTab(self.solutionsTab, _fromUtf8(""))
        self.horizontalLayout_22.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(3)
        self.weightTop.setCurrentIndex(0)
        self.solutionTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Domain:", None))
        self.label_2.setText(_translate("MainWindow", "Description:", None))
        self.label_3.setText(_translate("MainWindow", "Parameters:", None))
        self.label_4.setText(_translate("MainWindow", "Initial mesh size:", None))
        self.initSize.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "Initial refine: ", None))
        self.initRefine.setItemText(0, _translate("MainWindow", "uniform", None))
        self.initRefine.setItemText(1, _translate("MainWindow", "long edge", None))
        self.preview.setText(_translate("MainWindow", "Preview", None))
        self.solve.setText(_translate("MainWindow", "Solve", None))
        self.tabs.setTabText(self.tabs.indexOf(self.domainTab), _translate("MainWindow", "Domains", None))
        self.label_6.setText(_translate("MainWindow", "To be applied (double-click to remove):", None))
        self.label_9.setText(_translate("MainWindow", "Description:", None))
        self.label_7.setText(_translate("MainWindow", "Available (double-click to add):", None))
        self.label_8.setText(_translate("MainWindow", "Parameters of the selected transform:", None))
        self.updateTransformParams.setText(_translate("MainWindow", "Update parameters", None))
        self.checkBox.setText(_translate("MainWindow", "Rebuild mesh", None))
        self.beforeAdaptive.setText(_translate("MainWindow", "Before adaptive loop", None))
        self.previewTransformed.setText(_translate("MainWindow", "Preview", None))
        self.solve2.setText(_translate("MainWindow", "Solve", None))
        self.tabs.setTabText(self.tabs.indexOf(self.transformTab), _translate("MainWindow", "Transformations", None))
        self.label_10.setText(_translate("MainWindow", "To be applied (double-click to remove):", None))
        self.label_13.setText(_translate("MainWindow", "Description:", None))
        self.label_11.setText(_translate("MainWindow", "Available (double-click to add):", None))
        self.bcLabel.setText(_translate("MainWindow", "Parameter:", None))
        self.updateBCParams.setText(_translate("MainWindow", "Update boundary condition", None))
        self.useTransformed.setText(_translate("MainWindow", "Apply to transformed mesh", None))
        self.previewBC.setText(_translate("MainWindow", "Preview", None))
        self.solve3.setText(_translate("MainWindow", "Solve", None))
        self.tabs.setTabText(self.tabs.indexOf(self.bcTab), _translate("MainWindow", "Boundary Conditions", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Solver options:", None))
        self.label_15.setText(_translate("MainWindow", "FEM:", None))
        self.femType.setItemText(0, _translate("MainWindow", "conforming", None))
        self.femType.setItemText(1, _translate("MainWindow", "nonconforming", None))
        self.femType.setItemText(2, _translate("MainWindow", "lower bound", None))
        self.label_17.setText(_translate("MainWindow", "Degree:", None))
        self.label_16.setText(_translate("MainWindow", "Solve for:", None))
        self.solveType.setItemText(0, _translate("MainWindow", "smallest eigenvalues", None))
        self.solveType.setItemText(1, _translate("MainWindow", "eigenvalues close to", None))
        self.targetValue.setText(_translate("MainWindow", "0.0", None))
        self.adaptive.setText(_translate("MainWindow", "Adaptive solver", None))
        self.torsion.setText(_translate("MainWindow", "Find torsion function", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mesh options:", None))
        self.label_12.setText(_translate("MainWindow", "Final mesh size:", None))
        self.meshLimit.setItemText(0, _translate("MainWindow", "at least", None))
        self.meshLimit.setItemText(1, _translate("MainWindow", "at most", None))
        self.meshSize.setText(_translate("MainWindow", "10000", None))
        self.label_14.setText(_translate("MainWindow", "Refine:", None))
        self.refine.setItemText(0, _translate("MainWindow", "uniform", None))
        self.refine.setItemText(1, _translate("MainWindow", "long edge", None))
        self.snap.setText(_translate("MainWindow", "Snap to", None))
        self.snapType.setItemText(0, _translate("MainWindow", "radius function R(r, theta, eta)", None))
        self.snapType.setItemText(1, _translate("MainWindow", "revolution (R(r, theta), z)", None))
        self.snapType.setItemText(2, _translate("MainWindow", "width (F(y, z), y, z)", None))
        self.snapType.setItemText(3, _translate("MainWindow", "depth (x, F(x, z), z)", None))
        self.snapType.setItemText(4, _translate("MainWindow", "height (x, y, F(z))", None))
        self.label_18.setText(_translate("MainWindow", ":", None))
        self.groupBox.setTitle(_translate("MainWindow", "Adaptive solver options:", None))
        self.adaptiveSnap.setText(_translate("MainWindow", "Snap", None))
        self.label_21.setText(_translate("MainWindow", "% longest edges to the function from above", None))
        self.label_19.setText(_translate("MainWindow", "Refine worst", None))
        self.label_20.setText(_translate("MainWindow", "%", None))
        self.adaptiveType.setItemText(0, _translate("MainWindow", "by rank", None))
        self.adaptiveType.setItemText(1, _translate("MainWindow", "by value", None))
        self.label_22.setText(_translate("MainWindow", "Residual errors from", None))
        self.residualType.setItemText(0, _translate("MainWindow", "first nonzero eigenvalue", None))
        self.residualType.setItemText(1, _translate("MainWindow", "eigenvalue number", None))
        self.residualType.setItemText(2, _translate("MainWindow", "torsion function", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Weights for energy and norm integrals:", None))
        self.weightTop.setItemText(0, _translate("MainWindow", "None", None))
        self.weightTop.setItemText(1, _translate("MainWindow", "Gaussian", None))
        self.weightBottom.setItemText(0, _translate("MainWindow", "None", None))
        self.weightBottom.setItemText(1, _translate("MainWindow", "Gaussian", None))
        self.pushButton.setText(_translate("MainWindow", "Load Solution", None))
        self.solve4.setText(_translate("MainWindow", "Solve", None))
        self.label_24.setText(_translate("MainWindow", "Parameters:", None))
        self.pushButton_3.setText(_translate("MainWindow", "Load", None))
        self.pushButton_2.setText(_translate("MainWindow", "Save", None))
        self.label_23.setText(_translate("MainWindow", "Log:", None))
        self.tabs.setTabText(self.tabs.indexOf(self.otherTab), _translate("MainWindow", "Other options", None))
        self.tabs.setTabText(self.tabs.indexOf(self.solutionsTab), _translate("MainWindow", "Solutions", None))

