# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eigGUI.ui'
#
# Created: Sun Dec  6 23:54:48 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName("tabs")
        self.domainTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainTab.sizePolicy().hasHeightForWidth())
        self.domainTab.setSizePolicy(sizePolicy)
        self.domainTab.setObjectName("domainTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.domainTab)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.domains = QtWidgets.QListWidget(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domains.sizePolicy().hasHeightForWidth())
        self.domains.setSizePolicy(sizePolicy)
        self.domains.setMinimumSize(QtCore.QSize(300, 0))
        self.domains.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.domains.setObjectName("domains")
        self.verticalLayout.addWidget(self.domains)
        self.label_2 = QtWidgets.QLabel(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.description = QtWidgets.QPlainTextEdit(self.domainTab)
        self.description.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(300, 200))
        self.description.setMaximumSize(QtCore.QSize(16777215, 200))
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.parameters = QtWidgets.QComboBox(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters.sizePolicy().hasHeightForWidth())
        self.parameters.setSizePolicy(sizePolicy)
        self.parameters.setEditable(True)
        self.parameters.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.parameters.setObjectName("parameters")
        self.verticalLayout_2.addWidget(self.parameters)
        self.meshFrame = QtWidgets.QFrame(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshFrame.sizePolicy().hasHeightForWidth())
        self.meshFrame.setSizePolicy(sizePolicy)
        self.meshFrame.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.meshFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.meshFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.meshFrame.setObjectName("meshFrame")
        self.verticalLayout_2.addWidget(self.meshFrame)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.domainTab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.initSize = QtWidgets.QLineEdit(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initSize.sizePolicy().hasHeightForWidth())
        self.initSize.setSizePolicy(sizePolicy)
        self.initSize.setMinimumSize(QtCore.QSize(0, 0))
        self.initSize.setObjectName("initSize")
        self.horizontalLayout_2.addWidget(self.initSize)
        self.label_5 = QtWidgets.QLabel(self.domainTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.initRefine = QtWidgets.QComboBox(self.domainTab)
        self.initRefine.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initRefine.sizePolicy().hasHeightForWidth())
        self.initRefine.setSizePolicy(sizePolicy)
        self.initRefine.setObjectName("initRefine")
        self.initRefine.addItem("")
        self.initRefine.addItem("")
        self.horizontalLayout_2.addWidget(self.initRefine)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.preview = QtWidgets.QPushButton(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview.sizePolicy().hasHeightForWidth())
        self.preview.setSizePolicy(sizePolicy)
        self.preview.setObjectName("preview")
        self.horizontalLayout_2.addWidget(self.preview)
        self.solve = QtWidgets.QPushButton(self.domainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve.sizePolicy().hasHeightForWidth())
        self.solve.setSizePolicy(sizePolicy)
        self.solve.setObjectName("solve")
        self.horizontalLayout_2.addWidget(self.solve)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabs.addTab(self.domainTab, "")
        self.transformTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformTab.sizePolicy().hasHeightForWidth())
        self.transformTab.setSizePolicy(sizePolicy)
        self.transformTab.setObjectName("transformTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.transformTab)
        self.verticalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.selectedTransforms = QtWidgets.QListWidget(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedTransforms.sizePolicy().hasHeightForWidth())
        self.selectedTransforms.setSizePolicy(sizePolicy)
        self.selectedTransforms.setMinimumSize(QtCore.QSize(300, 0))
        self.selectedTransforms.setDragEnabled(True)
        self.selectedTransforms.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.selectedTransforms.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.selectedTransforms.setObjectName("selectedTransforms")
        self.verticalLayout_4.addWidget(self.selectedTransforms)
        self.label_9 = QtWidgets.QLabel(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.transformDescription = QtWidgets.QPlainTextEdit(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformDescription.sizePolicy().hasHeightForWidth())
        self.transformDescription.setSizePolicy(sizePolicy)
        self.transformDescription.setMaximumSize(QtCore.QSize(16777215, 150))
        self.transformDescription.setReadOnly(True)
        self.transformDescription.setObjectName("transformDescription")
        self.verticalLayout_4.addWidget(self.transformDescription)
        self.label_7 = QtWidgets.QLabel(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.transforms = QtWidgets.QListWidget(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transforms.sizePolicy().hasHeightForWidth())
        self.transforms.setSizePolicy(sizePolicy)
        self.transforms.setObjectName("transforms")
        self.verticalLayout_4.addWidget(self.transforms)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.updateTransformParams = QtWidgets.QPushButton(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTransformParams.sizePolicy().hasHeightForWidth())
        self.updateTransformParams.setSizePolicy(sizePolicy)
        self.updateTransformParams.setObjectName("updateTransformParams")
        self.horizontalLayout_4.addWidget(self.updateTransformParams)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.transformParameters = QtWidgets.QLineEdit(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformParameters.sizePolicy().hasHeightForWidth())
        self.transformParameters.setSizePolicy(sizePolicy)
        self.transformParameters.setObjectName("transformParameters")
        self.verticalLayout_6.addWidget(self.transformParameters)
        self.transformedMeshFrame = QtWidgets.QFrame(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transformedMeshFrame.sizePolicy().hasHeightForWidth())
        self.transformedMeshFrame.setSizePolicy(sizePolicy)
        self.transformedMeshFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transformedMeshFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transformedMeshFrame.setObjectName("transformedMeshFrame")
        self.verticalLayout_6.addWidget(self.transformedMeshFrame)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.transformTab)
        self.checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.beforeAdaptive = QtWidgets.QCheckBox(self.transformTab)
        self.beforeAdaptive.setEnabled(False)
        self.beforeAdaptive.setObjectName("beforeAdaptive")
        self.horizontalLayout_5.addWidget(self.beforeAdaptive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.previewTransformed = QtWidgets.QPushButton(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewTransformed.sizePolicy().hasHeightForWidth())
        self.previewTransformed.setSizePolicy(sizePolicy)
        self.previewTransformed.setObjectName("previewTransformed")
        self.horizontalLayout_5.addWidget(self.previewTransformed)
        self.solve2 = QtWidgets.QPushButton(self.transformTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve2.sizePolicy().hasHeightForWidth())
        self.solve2.setSizePolicy(sizePolicy)
        self.solve2.setObjectName("solve2")
        self.horizontalLayout_5.addWidget(self.solve2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.tabs.addTab(self.transformTab, "")
        self.bcTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcTab.sizePolicy().hasHeightForWidth())
        self.bcTab.setSizePolicy(sizePolicy)
        self.bcTab.setObjectName("bcTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.bcTab)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.selectedBC = QtWidgets.QListWidget(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedBC.sizePolicy().hasHeightForWidth())
        self.selectedBC.setSizePolicy(sizePolicy)
        self.selectedBC.setMinimumSize(QtCore.QSize(300, 0))
        self.selectedBC.setDragEnabled(True)
        self.selectedBC.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.selectedBC.setObjectName("selectedBC")
        self.verticalLayout_7.addWidget(self.selectedBC)
        self.label_13 = QtWidgets.QLabel(self.bcTab)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.bcDescription = QtWidgets.QPlainTextEdit(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcDescription.sizePolicy().hasHeightForWidth())
        self.bcDescription.setSizePolicy(sizePolicy)
        self.bcDescription.setMaximumSize(QtCore.QSize(16777215, 150))
        self.bcDescription.setReadOnly(True)
        self.bcDescription.setObjectName("bcDescription")
        self.verticalLayout_7.addWidget(self.bcDescription)
        self.label_11 = QtWidgets.QLabel(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.bcs = QtWidgets.QListWidget(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcs.sizePolicy().hasHeightForWidth())
        self.bcs.setSizePolicy(sizePolicy)
        self.bcs.setObjectName("bcs")
        self.verticalLayout_7.addWidget(self.bcs)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bcApplyTo = QtWidgets.QComboBox(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcApplyTo.sizePolicy().hasHeightForWidth())
        self.bcApplyTo.setSizePolicy(sizePolicy)
        self.bcApplyTo.setObjectName("bcApplyTo")
        self.horizontalLayout_8.addWidget(self.bcApplyTo)
        self.bcParts = QtWidgets.QLineEdit(self.bcTab)
        self.bcParts.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcParts.sizePolicy().hasHeightForWidth())
        self.bcParts.setSizePolicy(sizePolicy)
        self.bcParts.setObjectName("bcParts")
        self.horizontalLayout_8.addWidget(self.bcParts)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bcLabel = QtWidgets.QLabel(self.bcTab)
        self.bcLabel.setObjectName("bcLabel")
        self.horizontalLayout_9.addWidget(self.bcLabel)
        self.bcParameters = QtWidgets.QLineEdit(self.bcTab)
        self.bcParameters.setEnabled(True)
        self.bcParameters.setObjectName("bcParameters")
        self.horizontalLayout_9.addWidget(self.bcParameters)
        self.updateBCParams = QtWidgets.QPushButton(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateBCParams.sizePolicy().hasHeightForWidth())
        self.updateBCParams.setSizePolicy(sizePolicy)
        self.updateBCParams.setObjectName("updateBCParams")
        self.horizontalLayout_9.addWidget(self.updateBCParams)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.bcFrame = QtWidgets.QFrame(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcFrame.sizePolicy().hasHeightForWidth())
        self.bcFrame.setSizePolicy(sizePolicy)
        self.bcFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bcFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bcFrame.setObjectName("bcFrame")
        self.verticalLayout_9.addWidget(self.bcFrame)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.useTransformed = QtWidgets.QCheckBox(self.bcTab)
        self.useTransformed.setObjectName("useTransformed")
        self.horizontalLayout_7.addWidget(self.useTransformed)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.previewBC = QtWidgets.QPushButton(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewBC.sizePolicy().hasHeightForWidth())
        self.previewBC.setSizePolicy(sizePolicy)
        self.previewBC.setObjectName("previewBC")
        self.horizontalLayout_7.addWidget(self.previewBC)
        self.solve3 = QtWidgets.QPushButton(self.bcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve3.sizePolicy().hasHeightForWidth())
        self.solve3.setSizePolicy(sizePolicy)
        self.solve3.setObjectName("solve3")
        self.horizontalLayout_7.addWidget(self.solve3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.tabs.addTab(self.bcTab, "")
        self.otherTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherTab.sizePolicy().hasHeightForWidth())
        self.otherTab.setSizePolicy(sizePolicy)
        self.otherTab.setObjectName("otherTab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.otherTab)
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.otherTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.femType = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femType.sizePolicy().hasHeightForWidth())
        self.femType.setSizePolicy(sizePolicy)
        self.femType.setObjectName("femType")
        self.femType.addItem("")
        self.femType.addItem("")
        self.femType.addItem("")
        self.horizontalLayout_14.addWidget(self.femType)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.femDegree = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.femDegree.sizePolicy().hasHeightForWidth())
        self.femDegree.setSizePolicy(sizePolicy)
        self.femDegree.setMinimumSize(QtCore.QSize(60, 0))
        self.femDegree.setMaximumSize(QtCore.QSize(60, 16777215))
        self.femDegree.setMinimum(1)
        self.femDegree.setMaximum(3)
        self.femDegree.setProperty("value", 2)
        self.femDegree.setObjectName("femDegree")
        self.horizontalLayout_14.addWidget(self.femDegree)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.solveNumber = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solveNumber.sizePolicy().hasHeightForWidth())
        self.solveNumber.setSizePolicy(sizePolicy)
        self.solveNumber.setMinimumSize(QtCore.QSize(50, 0))
        self.solveNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.solveNumber.setMinimum(1)
        self.solveNumber.setMaximum(100)
        self.solveNumber.setProperty("value", 10)
        self.solveNumber.setObjectName("solveNumber")
        self.horizontalLayout_11.addWidget(self.solveNumber)
        self.solveType = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solveType.sizePolicy().hasHeightForWidth())
        self.solveType.setSizePolicy(sizePolicy)
        self.solveType.setMinimumSize(QtCore.QSize(165, 0))
        self.solveType.setMaximumSize(QtCore.QSize(165, 16777215))
        self.solveType.setObjectName("solveType")
        self.solveType.addItem("")
        self.solveType.addItem("")
        self.horizontalLayout_11.addWidget(self.solveType)
        self.targetValue = QtWidgets.QLineEdit(self.groupBox_3)
        self.targetValue.setEnabled(False)
        self.targetValue.setObjectName("targetValue")
        self.horizontalLayout_11.addWidget(self.targetValue)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.adaptive = QtWidgets.QCheckBox(self.groupBox_3)
        self.adaptive.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptive.sizePolicy().hasHeightForWidth())
        self.adaptive.setSizePolicy(sizePolicy)
        self.adaptive.setObjectName("adaptive")
        self.horizontalLayout_23.addWidget(self.adaptive)
        self.torsion = QtWidgets.QCheckBox(self.groupBox_3)
        self.torsion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torsion.sizePolicy().hasHeightForWidth())
        self.torsion.setSizePolicy(sizePolicy)
        self.torsion.setObjectName("torsion")
        self.horizontalLayout_23.addWidget(self.torsion)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.otherTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.meshLimit = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshLimit.sizePolicy().hasHeightForWidth())
        self.meshLimit.setSizePolicy(sizePolicy)
        self.meshLimit.setObjectName("meshLimit")
        self.meshLimit.addItem("")
        self.meshLimit.addItem("")
        self.horizontalLayout_10.addWidget(self.meshLimit)
        self.meshSize = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshSize.sizePolicy().hasHeightForWidth())
        self.meshSize.setSizePolicy(sizePolicy)
        self.meshSize.setObjectName("meshSize")
        self.horizontalLayout_10.addWidget(self.meshSize)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.refine = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refine.sizePolicy().hasHeightForWidth())
        self.refine.setSizePolicy(sizePolicy)
        self.refine.setObjectName("refine")
        self.refine.addItem("")
        self.refine.addItem("")
        self.horizontalLayout_12.addWidget(self.refine)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.snap = QtWidgets.QCheckBox(self.groupBox_2)
        self.snap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap.sizePolicy().hasHeightForWidth())
        self.snap.setSizePolicy(sizePolicy)
        self.snap.setObjectName("snap")
        self.horizontalLayout_15.addWidget(self.snap)
        self.snapType = QtWidgets.QComboBox(self.groupBox_2)
        self.snapType.setEnabled(False)
        self.snapType.setMinimumSize(QtCore.QSize(220, 0))
        self.snapType.setMaximumSize(QtCore.QSize(200, 16777215))
        self.snapType.setObjectName("snapType")
        self.snapType.addItem("")
        self.snapType.addItem("")
        self.snapType.addItem("")
        self.snapType.addItem("")
        self.snapType.addItem("")
        self.horizontalLayout_15.addWidget(self.snapType)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.snapFunction = QtWidgets.QLineEdit(self.groupBox_2)
        self.snapFunction.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapFunction.sizePolicy().hasHeightForWidth())
        self.snapFunction.setSizePolicy(sizePolicy)
        self.snapFunction.setMinimumSize(QtCore.QSize(400, 0))
        self.snapFunction.setMaximumSize(QtCore.QSize(400, 16777215))
        self.snapFunction.setObjectName("snapFunction")
        self.verticalLayout_13.addWidget(self.snapFunction)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.otherTab)
        self.groupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(430, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(430, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.adaptiveSnap = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptiveSnap.sizePolicy().hasHeightForWidth())
        self.adaptiveSnap.setSizePolicy(sizePolicy)
        self.adaptiveSnap.setObjectName("adaptiveSnap")
        self.horizontalLayout_18.addWidget(self.adaptiveSnap)
        self.snapPercent = QtWidgets.QSpinBox(self.groupBox)
        self.snapPercent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapPercent.sizePolicy().hasHeightForWidth())
        self.snapPercent.setSizePolicy(sizePolicy)
        self.snapPercent.setMinimumSize(QtCore.QSize(60, 0))
        self.snapPercent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.snapPercent.setMinimum(1)
        self.snapPercent.setMaximum(100)
        self.snapPercent.setProperty("value", 20)
        self.snapPercent.setObjectName("snapPercent")
        self.horizontalLayout_18.addWidget(self.snapPercent)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.adaptivePercent = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adaptivePercent.sizePolicy().hasHeightForWidth())
        self.adaptivePercent.setSizePolicy(sizePolicy)
        self.adaptivePercent.setMinimumSize(QtCore.QSize(60, 0))
        self.adaptivePercent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.adaptivePercent.setMinimum(1)
        self.adaptivePercent.setProperty("value", 20)
        self.adaptivePercent.setObjectName("adaptivePercent")
        self.horizontalLayout_17.addWidget(self.adaptivePercent)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.adaptiveType = QtWidgets.QComboBox(self.groupBox)
        self.adaptiveType.setObjectName("adaptiveType")
        self.adaptiveType.addItem("")
        self.adaptiveType.addItem("")
        self.horizontalLayout_17.addWidget(self.adaptiveType)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.residualType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.residualType.sizePolicy().hasHeightForWidth())
        self.residualType.setSizePolicy(sizePolicy)
        self.residualType.setMinimumSize(QtCore.QSize(180, 0))
        self.residualType.setObjectName("residualType")
        self.residualType.addItem("")
        self.residualType.addItem("")
        self.residualType.addItem("")
        self.horizontalLayout_19.addWidget(self.residualType)
        self.residualNumber = QtWidgets.QSpinBox(self.groupBox)
        self.residualNumber.setEnabled(False)
        self.residualNumber.setMinimum(1)
        self.residualNumber.setMaximum(100)
        self.residualNumber.setObjectName("residualNumber")
        self.horizontalLayout_19.addWidget(self.residualNumber)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.otherTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.weightTop = QtWidgets.QComboBox(self.groupBox_4)
        self.weightTop.setEditable(True)
        self.weightTop.setObjectName("weightTop")
        self.weightTop.addItem("")
        self.weightTop.addItem("")
        self.horizontalLayout_20.addWidget(self.weightTop)
        self.weightBottom = QtWidgets.QComboBox(self.groupBox_4)
        self.weightBottom.setEditable(True)
        self.weightBottom.setObjectName("weightBottom")
        self.weightBottom.addItem("")
        self.weightBottom.addItem("")
        self.horizontalLayout_20.addWidget(self.weightBottom)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.pushButton = QtWidgets.QPushButton(self.otherTab)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.solve4 = QtWidgets.QPushButton(self.otherTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve4.sizePolicy().hasHeightForWidth())
        self.solve4.setSizePolicy(sizePolicy)
        self.solve4.setMinimumSize(QtCore.QSize(167, 0))
        self.solve4.setMaximumSize(QtCore.QSize(167, 16777215))
        self.solve4.setObjectName("solve4")
        self.horizontalLayout_16.addWidget(self.solve4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.label_24 = QtWidgets.QLabel(self.otherTab)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.pushButton_3 = QtWidgets.QPushButton(self.otherTab)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_24.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.otherTab)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_24.addWidget(self.pushButton_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.label_23 = QtWidgets.QLabel(self.otherTab)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.stats = QtWidgets.QPlainTextEdit(self.otherTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats.sizePolicy().hasHeightForWidth())
        self.stats.setSizePolicy(sizePolicy)
        self.stats.setReadOnly(True)
        self.stats.setObjectName("stats")
        self.verticalLayout_12.addWidget(self.stats)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.tabs.addTab(self.otherTab, "")
        self.solutionsTab = QtWidgets.QWidget()
        self.solutionsTab.setObjectName("solutionsTab")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.solutionsTab)
        self.horizontalLayout_21.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.solutionTabs = QtWidgets.QTabWidget(self.solutionsTab)
        self.solutionTabs.setUsesScrollButtons(True)
        self.solutionTabs.setDocumentMode(True)
        self.solutionTabs.setTabsClosable(True)
        self.solutionTabs.setMovable(True)
        self.solutionTabs.setObjectName("solutionTabs")
        self.horizontalLayout_21.addWidget(self.solutionTabs)
        self.tabs.addTab(self.solutionsTab, "")
        self.horizontalLayout_22.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(3)
        self.weightTop.setCurrentIndex(0)
        self.solutionTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Domain:"))
        self.label_2.setText(_translate("MainWindow", "Description:"))
        self.label_3.setText(_translate("MainWindow", "Parameters:"))
        self.label_4.setText(_translate("MainWindow", "Initial mesh size:"))
        self.initSize.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "Initial refine: "))
        self.initRefine.setItemText(0, _translate("MainWindow", "uniform"))
        self.initRefine.setItemText(1, _translate("MainWindow", "long edge"))
        self.preview.setText(_translate("MainWindow", "Preview"))
        self.solve.setText(_translate("MainWindow", "Solve"))
        self.tabs.setTabText(self.tabs.indexOf(self.domainTab), _translate("MainWindow", "Domains"))
        self.label_6.setText(_translate("MainWindow", "To be applied (double-click to remove):"))
        self.label_9.setText(_translate("MainWindow", "Description:"))
        self.label_7.setText(_translate("MainWindow", "Available (double-click to add):"))
        self.label_8.setText(_translate("MainWindow", "Parameters of the selected transform:"))
        self.updateTransformParams.setText(_translate("MainWindow", "Update parameters"))
        self.checkBox.setText(_translate("MainWindow", "Rebuild mesh"))
        self.beforeAdaptive.setText(_translate("MainWindow", "Before adaptive loop"))
        self.previewTransformed.setText(_translate("MainWindow", "Preview"))
        self.solve2.setText(_translate("MainWindow", "Solve"))
        self.tabs.setTabText(self.tabs.indexOf(self.transformTab), _translate("MainWindow", "Transformations"))
        self.label_10.setText(_translate("MainWindow", "To be applied (double-click to remove):"))
        self.label_13.setText(_translate("MainWindow", "Description:"))
        self.label_11.setText(_translate("MainWindow", "Available (double-click to add):"))
        self.bcLabel.setText(_translate("MainWindow", "Parameter:"))
        self.updateBCParams.setText(_translate("MainWindow", "Update boundary condition"))
        self.useTransformed.setText(_translate("MainWindow", "Apply to transformed mesh"))
        self.previewBC.setText(_translate("MainWindow", "Preview"))
        self.solve3.setText(_translate("MainWindow", "Solve"))
        self.tabs.setTabText(self.tabs.indexOf(self.bcTab), _translate("MainWindow", "Boundary Conditions"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Solver options:"))
        self.label_15.setText(_translate("MainWindow", "FEM:"))
        self.femType.setItemText(0, _translate("MainWindow", "conforming"))
        self.femType.setItemText(1, _translate("MainWindow", "nonconforming"))
        self.femType.setItemText(2, _translate("MainWindow", "lower bound"))
        self.label_17.setText(_translate("MainWindow", "Degree:"))
        self.label_16.setText(_translate("MainWindow", "Solve for:"))
        self.solveType.setItemText(0, _translate("MainWindow", "smallest eigenvalues"))
        self.solveType.setItemText(1, _translate("MainWindow", "eigenvalues close to"))
        self.targetValue.setText(_translate("MainWindow", "0.0"))
        self.adaptive.setText(_translate("MainWindow", "Adaptive solver"))
        self.torsion.setText(_translate("MainWindow", "Find torsion function"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mesh options:"))
        self.label_12.setText(_translate("MainWindow", "Final mesh size:"))
        self.meshLimit.setItemText(0, _translate("MainWindow", "at least"))
        self.meshLimit.setItemText(1, _translate("MainWindow", "at most"))
        self.meshSize.setText(_translate("MainWindow", "10000"))
        self.label_14.setText(_translate("MainWindow", "Refine:"))
        self.refine.setItemText(0, _translate("MainWindow", "uniform"))
        self.refine.setItemText(1, _translate("MainWindow", "long edge"))
        self.snap.setText(_translate("MainWindow", "Snap to"))
        self.snapType.setItemText(0, _translate("MainWindow", "radius function R(r, theta, eta)"))
        self.snapType.setItemText(1, _translate("MainWindow", "revolution (R(r, theta), z)"))
        self.snapType.setItemText(2, _translate("MainWindow", "width (F(y, z), y, z)"))
        self.snapType.setItemText(3, _translate("MainWindow", "depth (x, F(x, z), z)"))
        self.snapType.setItemText(4, _translate("MainWindow", "height (x, y, F(z))"))
        self.label_18.setText(_translate("MainWindow", ":"))
        self.groupBox.setTitle(_translate("MainWindow", "Adaptive solver options:"))
        self.adaptiveSnap.setText(_translate("MainWindow", "Snap"))
        self.label_21.setText(_translate("MainWindow", "% longest edges to the function from above"))
        self.label_19.setText(_translate("MainWindow", "Refine worst"))
        self.label_20.setText(_translate("MainWindow", "%"))
        self.adaptiveType.setItemText(0, _translate("MainWindow", "by rank"))
        self.adaptiveType.setItemText(1, _translate("MainWindow", "by value"))
        self.label_22.setText(_translate("MainWindow", "Residual errors from"))
        self.residualType.setItemText(0, _translate("MainWindow", "first nonzero eigenvalue"))
        self.residualType.setItemText(1, _translate("MainWindow", "eigenvalue number"))
        self.residualType.setItemText(2, _translate("MainWindow", "torsion function"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Weights for energy and norm integrals:"))
        self.weightTop.setItemText(0, _translate("MainWindow", "None"))
        self.weightTop.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.weightBottom.setItemText(0, _translate("MainWindow", "None"))
        self.weightBottom.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.pushButton.setText(_translate("MainWindow", "Load Solution"))
        self.solve4.setText(_translate("MainWindow", "Solve"))
        self.label_24.setText(_translate("MainWindow", "Parameters:"))
        self.pushButton_3.setText(_translate("MainWindow", "Load"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.label_23.setText(_translate("MainWindow", "Log:"))
        self.tabs.setTabText(self.tabs.indexOf(self.otherTab), _translate("MainWindow", "Other options"))
        self.tabs.setTabText(self.tabs.indexOf(self.solutionsTab), _translate("MainWindow", "Solutions"))

