# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutiontab.ui'
#
# Created: Sun Dec  6 23:54:48 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SolutionTab(object):
    def setupUi(self, SolutionTab):
        SolutionTab.setObjectName("SolutionTab")
        SolutionTab.resize(1244, 621)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SolutionTab)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SolutionTab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.eigList = QtWidgets.QListWidget(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eigList.sizePolicy().hasHeightForWidth())
        self.eigList.setSizePolicy(sizePolicy)
        self.eigList.setMinimumSize(QtCore.QSize(250, 0))
        self.eigList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.eigList.setObjectName("eigList")
        self.verticalLayout.addWidget(self.eigList)
        self.label_3 = QtWidgets.QLabel(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.functional = QtWidgets.QLineEdit(SolutionTab)
        self.functional.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functional.sizePolicy().hasHeightForWidth())
        self.functional.setSizePolicy(sizePolicy)
        self.functional.setMinimumSize(QtCore.QSize(250, 0))
        self.functional.setMaximumSize(QtCore.QSize(250, 16777215))
        self.functional.setObjectName("functional")
        self.verticalLayout.addWidget(self.functional)
        self.label_5 = QtWidgets.QLabel(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.eigenfunctionFunctional = QtWidgets.QLineEdit(SolutionTab)
        self.eigenfunctionFunctional.setEnabled(False)
        self.eigenfunctionFunctional.setMinimumSize(QtCore.QSize(250, 0))
        self.eigenfunctionFunctional.setMaximumSize(QtCore.QSize(250, 16777215))
        self.eigenfunctionFunctional.setObjectName("eigenfunctionFunctional")
        self.verticalLayout.addWidget(self.eigenfunctionFunctional)
        self.groupBox_2 = QtWidgets.QGroupBox(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.contours = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contours.sizePolicy().hasHeightForWidth())
        self.contours.setSizePolicy(sizePolicy)
        self.contours.setChecked(True)
        self.contours.setAutoExclusive(True)
        self.contours.setObjectName("contours")
        self.gridLayout.addWidget(self.contours, 0, 0, 1, 1)
        self.numContours = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numContours.sizePolicy().hasHeightForWidth())
        self.numContours.setSizePolicy(sizePolicy)
        self.numContours.setMinimumSize(QtCore.QSize(50, 0))
        self.numContours.setMaximumSize(QtCore.QSize(50, 16777215))
        self.numContours.setMinimum(0)
        self.numContours.setMaximum(99)
        self.numContours.setProperty("value", 10)
        self.numContours.setObjectName("numContours")
        self.gridLayout.addWidget(self.numContours, 0, 2, 1, 1)
        self.grayscale = QtWidgets.QCheckBox(self.groupBox_2)
        self.grayscale.setObjectName("grayscale")
        self.gridLayout.addWidget(self.grayscale, 1, 3, 1, 1)
        self.surface = QtWidgets.QCheckBox(self.groupBox_2)
        self.surface.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surface.sizePolicy().hasHeightForWidth())
        self.surface.setSizePolicy(sizePolicy)
        self.surface.setAutoExclusive(True)
        self.surface.setObjectName("surface")
        self.gridLayout.addWidget(self.surface, 1, 0, 1, 1)
        self.flip = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flip.sizePolicy().hasHeightForWidth())
        self.flip.setSizePolicy(sizePolicy)
        self.flip.setObjectName("flip")
        self.gridLayout.addWidget(self.flip, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_2 = QtWidgets.QLabel(SolutionTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.domainData = QtWidgets.QTextEdit(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainData.sizePolicy().hasHeightForWidth())
        self.domainData.setSizePolicy(sizePolicy)
        self.domainData.setMinimumSize(QtCore.QSize(250, 150))
        self.domainData.setMaximumSize(QtCore.QSize(250, 150))
        self.domainData.setReadOnly(True)
        self.domainData.setObjectName("domainData")
        self.verticalLayout.addWidget(self.domainData)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.genPlot = QtWidgets.QPushButton(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genPlot.sizePolicy().hasHeightForWidth())
        self.genPlot.setSizePolicy(sizePolicy)
        self.genPlot.setMinimumSize(QtCore.QSize(150, 0))
        self.genPlot.setMaximumSize(QtCore.QSize(200, 16777215))
        self.genPlot.setObjectName("genPlot")
        self.horizontalLayout_3.addWidget(self.genPlot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.saveSolution = QtWidgets.QPushButton(SolutionTab)
        self.saveSolution.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSolution.sizePolicy().hasHeightForWidth())
        self.saveSolution.setSizePolicy(sizePolicy)
        self.saveSolution.setObjectName("saveSolution")
        self.horizontalLayout_3.addWidget(self.saveSolution)
        self.label_7 = QtWidgets.QLabel(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.pushButton_2 = QtWidgets.QPushButton(SolutionTab)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(SolutionTab)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.symBox = QtWidgets.QGroupBox(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symBox.sizePolicy().hasHeightForWidth())
        self.symBox.setSizePolicy(sizePolicy)
        self.symBox.setObjectName("symBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.symBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.symX = QtWidgets.QSpinBox(self.symBox)
        self.symX.setMinimumSize(QtCore.QSize(40, 0))
        self.symX.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symX.setMinimum(-9)
        self.symX.setMaximum(9)
        self.symX.setObjectName("symX")
        self.horizontalLayout_2.addWidget(self.symX)
        self.label_6 = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.symY = QtWidgets.QSpinBox(self.symBox)
        self.symY.setMinimumSize(QtCore.QSize(40, 0))
        self.symY.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symY.setMinimum(-9)
        self.symY.setMaximum(9)
        self.symY.setObjectName("symY")
        self.horizontalLayout_2.addWidget(self.symY)
        self.labelZ = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelZ.sizePolicy().hasHeightForWidth())
        self.labelZ.setSizePolicy(sizePolicy)
        self.labelZ.setObjectName("labelZ")
        self.horizontalLayout_2.addWidget(self.labelZ)
        self.symZ = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symZ.sizePolicy().hasHeightForWidth())
        self.symZ.setSizePolicy(sizePolicy)
        self.symZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symZ.setMinimum(-9)
        self.symZ.setMaximum(9)
        self.symZ.setObjectName("symZ")
        self.horizontalLayout_2.addWidget(self.symZ)
        self.label_8 = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.symXY = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXY.sizePolicy().hasHeightForWidth())
        self.symXY.setSizePolicy(sizePolicy)
        self.symXY.setMinimumSize(QtCore.QSize(40, 0))
        self.symXY.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXY.setMinimum(-9)
        self.symXY.setMaximum(9)
        self.symXY.setObjectName("symXY")
        self.horizontalLayout_2.addWidget(self.symXY)
        self.labelXZ = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXZ.sizePolicy().hasHeightForWidth())
        self.labelXZ.setSizePolicy(sizePolicy)
        self.labelXZ.setObjectName("labelXZ")
        self.horizontalLayout_2.addWidget(self.labelXZ)
        self.symXZ = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXZ.sizePolicy().hasHeightForWidth())
        self.symXZ.setSizePolicy(sizePolicy)
        self.symXZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symXZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXZ.setMinimum(-9)
        self.symXZ.setMaximum(9)
        self.symXZ.setObjectName("symXZ")
        self.horizontalLayout_2.addWidget(self.symXZ)
        self.labelYZ = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelYZ.sizePolicy().hasHeightForWidth())
        self.labelYZ.setSizePolicy(sizePolicy)
        self.labelYZ.setObjectName("labelYZ")
        self.horizontalLayout_2.addWidget(self.labelYZ)
        self.symYZ = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symYZ.sizePolicy().hasHeightForWidth())
        self.symYZ.setSizePolicy(sizePolicy)
        self.symYZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symYZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symYZ.setMinimum(-9)
        self.symYZ.setMaximum(9)
        self.symYZ.setObjectName("symYZ")
        self.horizontalLayout_2.addWidget(self.symYZ)
        self.line_2 = QtWidgets.QFrame(self.symBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelXYZ = QtWidgets.QLabel(self.symBox)
        self.labelXYZ.setObjectName("labelXYZ")
        self.horizontalLayout_2.addWidget(self.labelXYZ)
        self.symXYZ = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXYZ.sizePolicy().hasHeightForWidth())
        self.symXYZ.setSizePolicy(sizePolicy)
        self.symXYZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symXYZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXYZ.setMinimum(0)
        self.symXYZ.setMaximum(9)
        self.symXYZ.setObjectName("symXYZ")
        self.horizontalLayout_2.addWidget(self.symXYZ)
        self.rotations = QtWidgets.QSpinBox(self.symBox)
        self.rotations.setEnabled(False)
        self.rotations.setMinimum(2)
        self.rotations.setProperty("value", 3)
        self.rotations.setObjectName("rotations")
        self.horizontalLayout_2.addWidget(self.rotations)
        self.labelRotations = QtWidgets.QLabel(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRotations.sizePolicy().hasHeightForWidth())
        self.labelRotations.setSizePolicy(sizePolicy)
        self.labelRotations.setObjectName("labelRotations")
        self.horizontalLayout_2.addWidget(self.labelRotations)
        self.symXXXX = QtWidgets.QSpinBox(self.symBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXXXX.sizePolicy().hasHeightForWidth())
        self.symXXXX.setSizePolicy(sizePolicy)
        self.symXXXX.setMinimumSize(QtCore.QSize(40, 0))
        self.symXXXX.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXXXX.setMaximum(9)
        self.symXXXX.setObjectName("symXXXX")
        self.horizontalLayout_2.addWidget(self.symXXXX)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.symBox)
        self.eigenFrame = QtWidgets.QFrame(SolutionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eigenFrame.sizePolicy().hasHeightForWidth())
        self.eigenFrame.setSizePolicy(sizePolicy)
        self.eigenFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eigenFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eigenFrame.setObjectName("eigenFrame")
        self.verticalLayout_3.addWidget(self.eigenFrame)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SolutionTab)
        QtCore.QMetaObject.connectSlotsByName(SolutionTab)

    def retranslateUi(self, SolutionTab):
        _translate = QtCore.QCoreApplication.translate
        SolutionTab.setWindowTitle(_translate("SolutionTab", "SolutionTab"))
        self.label.setText(_translate("SolutionTab", "Eigenvalues:"))
        self.label_3.setText(_translate("SolutionTab", "Scale eigenvalues using:"))
        self.functional.setText(_translate("SolutionTab", "1"))
        self.label_5.setText(_translate("SolutionTab", "Eigenfunction functional:"))
        self.eigenfunctionFunctional.setText(_translate("SolutionTab", "u"))
        self.groupBox_2.setTitle(_translate("SolutionTab", "Plot type:"))
        self.contours.setText(_translate("SolutionTab", "Contours"))
        self.grayscale.setText(_translate("SolutionTab", "Grayscale"))
        self.surface.setText(_translate("SolutionTab", "Surface"))
        self.flip.setText(_translate("SolutionTab", "Flip sign"))
        self.label_2.setText(_translate("SolutionTab", "Domain and solver:"))
        self.genPlot.setText(_translate("SolutionTab", "Generate plot"))
        self.saveSolution.setText(_translate("SolutionTab", "Save Solution"))
        self.label_7.setText(_translate("SolutionTab", "Parameters:"))
        self.pushButton_2.setText(_translate("SolutionTab", "Copy"))
        self.pushButton.setText(_translate("SolutionTab", "Save"))
        self.symBox.setTitle(_translate("SolutionTab", "Symmetrize eigenfunction (number - order of symmetrizations, negative - antisymmetry):"))
        self.label_4.setText(_translate("SolutionTab", " x"))
        self.label_6.setText(_translate("SolutionTab", " y"))
        self.labelZ.setText(_translate("SolutionTab", " z"))
        self.label_8.setText(_translate("SolutionTab", " xy"))
        self.labelXZ.setText(_translate("SolutionTab", " xz"))
        self.labelYZ.setText(_translate("SolutionTab", " yz"))
        self.labelXYZ.setText(_translate("SolutionTab", "Cycle xyz"))
        self.labelRotations.setText(_translate("SolutionTab", "-fold rotational symmetry"))

