# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutiontab.ui'
#
# Created: Sun Dec  6 23:54:48 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SolutionTab(object):
    def setupUi(self, SolutionTab):
        SolutionTab.setObjectName(_fromUtf8("SolutionTab"))
        SolutionTab.resize(1244, 621)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SolutionTab)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(SolutionTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.eigList = QtGui.QListWidget(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eigList.sizePolicy().hasHeightForWidth())
        self.eigList.setSizePolicy(sizePolicy)
        self.eigList.setMinimumSize(QtCore.QSize(250, 0))
        self.eigList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.eigList.setObjectName(_fromUtf8("eigList"))
        self.verticalLayout.addWidget(self.eigList)
        self.label_3 = QtGui.QLabel(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.functional = QtGui.QLineEdit(SolutionTab)
        self.functional.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functional.sizePolicy().hasHeightForWidth())
        self.functional.setSizePolicy(sizePolicy)
        self.functional.setMinimumSize(QtCore.QSize(250, 0))
        self.functional.setMaximumSize(QtCore.QSize(250, 16777215))
        self.functional.setObjectName(_fromUtf8("functional"))
        self.verticalLayout.addWidget(self.functional)
        self.label_5 = QtGui.QLabel(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.eigenfunctionFunctional = QtGui.QLineEdit(SolutionTab)
        self.eigenfunctionFunctional.setEnabled(False)
        self.eigenfunctionFunctional.setMinimumSize(QtCore.QSize(250, 0))
        self.eigenfunctionFunctional.setMaximumSize(QtCore.QSize(250, 16777215))
        self.eigenfunctionFunctional.setObjectName(_fromUtf8("eigenfunctionFunctional"))
        self.verticalLayout.addWidget(self.eigenfunctionFunctional)
        self.groupBox_2 = QtGui.QGroupBox(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.contours = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contours.sizePolicy().hasHeightForWidth())
        self.contours.setSizePolicy(sizePolicy)
        self.contours.setChecked(True)
        self.contours.setAutoExclusive(True)
        self.contours.setObjectName(_fromUtf8("contours"))
        self.gridLayout.addWidget(self.contours, 0, 0, 1, 1)
        self.numContours = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numContours.sizePolicy().hasHeightForWidth())
        self.numContours.setSizePolicy(sizePolicy)
        self.numContours.setMinimumSize(QtCore.QSize(50, 0))
        self.numContours.setMaximumSize(QtCore.QSize(50, 16777215))
        self.numContours.setMinimum(0)
        self.numContours.setMaximum(99)
        self.numContours.setProperty("value", 10)
        self.numContours.setObjectName(_fromUtf8("numContours"))
        self.gridLayout.addWidget(self.numContours, 0, 2, 1, 1)
        self.grayscale = QtGui.QCheckBox(self.groupBox_2)
        self.grayscale.setObjectName(_fromUtf8("grayscale"))
        self.gridLayout.addWidget(self.grayscale, 1, 3, 1, 1)
        self.surface = QtGui.QCheckBox(self.groupBox_2)
        self.surface.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surface.sizePolicy().hasHeightForWidth())
        self.surface.setSizePolicy(sizePolicy)
        self.surface.setAutoExclusive(True)
        self.surface.setObjectName(_fromUtf8("surface"))
        self.gridLayout.addWidget(self.surface, 1, 0, 1, 1)
        self.flip = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flip.sizePolicy().hasHeightForWidth())
        self.flip.setSizePolicy(sizePolicy)
        self.flip.setObjectName(_fromUtf8("flip"))
        self.gridLayout.addWidget(self.flip, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_2 = QtGui.QLabel(SolutionTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.domainData = QtGui.QTextEdit(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domainData.sizePolicy().hasHeightForWidth())
        self.domainData.setSizePolicy(sizePolicy)
        self.domainData.setMinimumSize(QtCore.QSize(250, 150))
        self.domainData.setMaximumSize(QtCore.QSize(250, 150))
        self.domainData.setReadOnly(True)
        self.domainData.setObjectName(_fromUtf8("domainData"))
        self.verticalLayout.addWidget(self.domainData)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.genPlot = QtGui.QPushButton(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genPlot.sizePolicy().hasHeightForWidth())
        self.genPlot.setSizePolicy(sizePolicy)
        self.genPlot.setMinimumSize(QtCore.QSize(150, 0))
        self.genPlot.setMaximumSize(QtCore.QSize(200, 16777215))
        self.genPlot.setObjectName(_fromUtf8("genPlot"))
        self.horizontalLayout_3.addWidget(self.genPlot)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.saveSolution = QtGui.QPushButton(SolutionTab)
        self.saveSolution.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSolution.sizePolicy().hasHeightForWidth())
        self.saveSolution.setSizePolicy(sizePolicy)
        self.saveSolution.setObjectName(_fromUtf8("saveSolution"))
        self.horizontalLayout_3.addWidget(self.saveSolution)
        self.label_7 = QtGui.QLabel(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.pushButton_2 = QtGui.QPushButton(SolutionTab)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(SolutionTab)
        self.pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.symBox = QtGui.QGroupBox(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symBox.sizePolicy().hasHeightForWidth())
        self.symBox.setSizePolicy(sizePolicy)
        self.symBox.setObjectName(_fromUtf8("symBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.symBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.symX = QtGui.QSpinBox(self.symBox)
        self.symX.setMinimumSize(QtCore.QSize(40, 0))
        self.symX.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symX.setMinimum(-9)
        self.symX.setMaximum(9)
        self.symX.setObjectName(_fromUtf8("symX"))
        self.horizontalLayout_2.addWidget(self.symX)
        self.label_6 = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.symY = QtGui.QSpinBox(self.symBox)
        self.symY.setMinimumSize(QtCore.QSize(40, 0))
        self.symY.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symY.setMinimum(-9)
        self.symY.setMaximum(9)
        self.symY.setObjectName(_fromUtf8("symY"))
        self.horizontalLayout_2.addWidget(self.symY)
        self.labelZ = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelZ.sizePolicy().hasHeightForWidth())
        self.labelZ.setSizePolicy(sizePolicy)
        self.labelZ.setObjectName(_fromUtf8("labelZ"))
        self.horizontalLayout_2.addWidget(self.labelZ)
        self.symZ = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symZ.sizePolicy().hasHeightForWidth())
        self.symZ.setSizePolicy(sizePolicy)
        self.symZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symZ.setMinimum(-9)
        self.symZ.setMaximum(9)
        self.symZ.setObjectName(_fromUtf8("symZ"))
        self.horizontalLayout_2.addWidget(self.symZ)
        self.label_8 = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.symXY = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXY.sizePolicy().hasHeightForWidth())
        self.symXY.setSizePolicy(sizePolicy)
        self.symXY.setMinimumSize(QtCore.QSize(40, 0))
        self.symXY.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXY.setMinimum(-9)
        self.symXY.setMaximum(9)
        self.symXY.setObjectName(_fromUtf8("symXY"))
        self.horizontalLayout_2.addWidget(self.symXY)
        self.labelXZ = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXZ.sizePolicy().hasHeightForWidth())
        self.labelXZ.setSizePolicy(sizePolicy)
        self.labelXZ.setObjectName(_fromUtf8("labelXZ"))
        self.horizontalLayout_2.addWidget(self.labelXZ)
        self.symXZ = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXZ.sizePolicy().hasHeightForWidth())
        self.symXZ.setSizePolicy(sizePolicy)
        self.symXZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symXZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXZ.setMinimum(-9)
        self.symXZ.setMaximum(9)
        self.symXZ.setObjectName(_fromUtf8("symXZ"))
        self.horizontalLayout_2.addWidget(self.symXZ)
        self.labelYZ = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelYZ.sizePolicy().hasHeightForWidth())
        self.labelYZ.setSizePolicy(sizePolicy)
        self.labelYZ.setObjectName(_fromUtf8("labelYZ"))
        self.horizontalLayout_2.addWidget(self.labelYZ)
        self.symYZ = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symYZ.sizePolicy().hasHeightForWidth())
        self.symYZ.setSizePolicy(sizePolicy)
        self.symYZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symYZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symYZ.setMinimum(-9)
        self.symYZ.setMaximum(9)
        self.symYZ.setObjectName(_fromUtf8("symYZ"))
        self.horizontalLayout_2.addWidget(self.symYZ)
        self.line_2 = QtGui.QFrame(self.symBox)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelXYZ = QtGui.QLabel(self.symBox)
        self.labelXYZ.setObjectName(_fromUtf8("labelXYZ"))
        self.horizontalLayout_2.addWidget(self.labelXYZ)
        self.symXYZ = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXYZ.sizePolicy().hasHeightForWidth())
        self.symXYZ.setSizePolicy(sizePolicy)
        self.symXYZ.setMinimumSize(QtCore.QSize(40, 0))
        self.symXYZ.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXYZ.setMinimum(0)
        self.symXYZ.setMaximum(9)
        self.symXYZ.setObjectName(_fromUtf8("symXYZ"))
        self.horizontalLayout_2.addWidget(self.symXYZ)
        self.rotations = QtGui.QSpinBox(self.symBox)
        self.rotations.setEnabled(False)
        self.rotations.setMinimum(2)
        self.rotations.setProperty("value", 3)
        self.rotations.setObjectName(_fromUtf8("rotations"))
        self.horizontalLayout_2.addWidget(self.rotations)
        self.labelRotations = QtGui.QLabel(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRotations.sizePolicy().hasHeightForWidth())
        self.labelRotations.setSizePolicy(sizePolicy)
        self.labelRotations.setObjectName(_fromUtf8("labelRotations"))
        self.horizontalLayout_2.addWidget(self.labelRotations)
        self.symXXXX = QtGui.QSpinBox(self.symBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symXXXX.sizePolicy().hasHeightForWidth())
        self.symXXXX.setSizePolicy(sizePolicy)
        self.symXXXX.setMinimumSize(QtCore.QSize(40, 0))
        self.symXXXX.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symXXXX.setMaximum(9)
        self.symXXXX.setObjectName(_fromUtf8("symXXXX"))
        self.horizontalLayout_2.addWidget(self.symXXXX)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.symBox)
        self.eigenFrame = QtGui.QFrame(SolutionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eigenFrame.sizePolicy().hasHeightForWidth())
        self.eigenFrame.setSizePolicy(sizePolicy)
        self.eigenFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.eigenFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.eigenFrame.setObjectName(_fromUtf8("eigenFrame"))
        self.verticalLayout_3.addWidget(self.eigenFrame)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SolutionTab)
        QtCore.QMetaObject.connectSlotsByName(SolutionTab)

    def retranslateUi(self, SolutionTab):
        SolutionTab.setWindowTitle(_translate("SolutionTab", "SolutionTab", None))
        self.label.setText(_translate("SolutionTab", "Eigenvalues:", None))
        self.label_3.setText(_translate("SolutionTab", "Scale eigenvalues using:", None))
        self.functional.setText(_translate("SolutionTab", "1", None))
        self.label_5.setText(_translate("SolutionTab", "Eigenfunction functional:", None))
        self.eigenfunctionFunctional.setText(_translate("SolutionTab", "u", None))
        self.groupBox_2.setTitle(_translate("SolutionTab", "Plot type:", None))
        self.contours.setText(_translate("SolutionTab", "Contours", None))
        self.grayscale.setText(_translate("SolutionTab", "Grayscale", None))
        self.surface.setText(_translate("SolutionTab", "Surface", None))
        self.flip.setText(_translate("SolutionTab", "Flip sign", None))
        self.label_2.setText(_translate("SolutionTab", "Domain and solver:", None))
        self.genPlot.setText(_translate("SolutionTab", "Generate plot", None))
        self.saveSolution.setText(_translate("SolutionTab", "Save Solution", None))
        self.label_7.setText(_translate("SolutionTab", "Parameters:", None))
        self.pushButton_2.setText(_translate("SolutionTab", "Copy", None))
        self.pushButton.setText(_translate("SolutionTab", "Save", None))
        self.symBox.setTitle(_translate("SolutionTab", "Symmetrize eigenfunction (number - order of symmetrizations, negative - antisymmetry):", None))
        self.label_4.setText(_translate("SolutionTab", " x", None))
        self.label_6.setText(_translate("SolutionTab", " y", None))
        self.labelZ.setText(_translate("SolutionTab", " z", None))
        self.label_8.setText(_translate("SolutionTab", " xy", None))
        self.labelXZ.setText(_translate("SolutionTab", " xz", None))
        self.labelYZ.setText(_translate("SolutionTab", " yz", None))
        self.labelXYZ.setText(_translate("SolutionTab", "Cycle xyz", None))
        self.labelRotations.setText(_translate("SolutionTab", "-fold rotational symmetry", None))

