#!/usr/bin/python
""" Run py2app and fix remaining problems. """
import os

dist = '/Users/siudeja/compile/eigenvalues/dist'
contents = dist + '/Eigenvalues.app/Contents'
os.chdir("../")
os.system('python py2app/setup.py py2app '
          '-b/Users/siudeja/compile/eigenvalues/build -d{}'.format(dist))

# symlink to python instead of python executable
os.system('rm '+contents+'/MacOS/python')
os.system('ln -s /usr/bin/python '+contents+'/MacOS/python')

# __init__.py missing from PyQt5 package
dynlibpyqt = contents+'/Resources/lib/python2.7/lib-dynload/PyQt5'
os.system('echo "#" > {0}/__init__.py'.format(dynlibpyqt))

# billiard has a c component
os.system('cp /Library/Python/2.7/site-packages/_billiard.so {}/../'
          .format(dynlibpyqt))

# debug Qt frameworks not needed
os.system('find {}/Frameworks/ -name "*_debug*" -delete'.format(contents))
os.system('find {}/Frameworks/ -name "*.prl" -delete'.format(contents))

# El Capitan does not allow relative paths in libraries
path = '/Applications/Eigenvalues.app/Contents'
frame = contents + '/Frameworks/{0}.framework/Versions/5/{0}'
libs = [dynlibpyqt + '/QtCore.so', dynlibpyqt + '/QtWidgets.so',
        dynlibpyqt + '/QtGui.so',
        contents + '/Resources/qt_plugins/platforms/libqcocoa.dylib'] + \
    [frame.format(e) for e in ('QtWidgets', 'QtGui', 'QtPrintSupport')]

# run install_name_tool on Qt libraries
for lib in libs:
    deps = os.popen('''otool -L ''' + lib)
    for dep in deps:
        dep = dep.split()[0].strip()
        if dep.startswith('@exe'):
            os.system('install_name_tool -change %s %s %s'
                      % (dep, dep.replace('@executable_path/..', path), lib))

# compress the app
import tarfile

os.chdir('osx')

with tarfile.open("Eigenvalues.app.tar.gz", "w:gz") as tar:
    os.chdir(dist)
    tar.add("Eigenvalues.app")
    tar.close()
